events { }
http {
	include mime.types;
        server {
                location / { 
                        root /etc/nginx/data/www/html;
                        index index.html;
                }

        }
}
